name: Build WF
on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v20

      - name: Maven Build
        run: maven install

  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code Checkout
        uses: actions/checkout@v16

      - name: Run tests on main branch
        run: maven test
      
      - name: Checkstyle
        run: mvn checkstyle:checkstyle