name: Build WF
on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: "50 3 * * *"
  
  permission:
    contents: read

####$$
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Maven Build
        run: mvn install

      - name: Upload Build Artifacts (WAR)
        uses: actions/upload-artifact@v4
        with:
          name: vprofile-app
          path: target/*.war

      - name: Notify if build fails
        if: failure()
        run: echo "Build failed! Please check the logs."
        
  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Run tests on main branch
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle